version: '3.7'
services:
  keys_api:
    container_name: keys_api
    build:
      context: .
      target: development
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    command: yarn start:debug
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    networks:
      - laxnet
    depends_on: 
      - sql
    networks:
      - xmpp_chat
  sql:
    container_name: xmpp_db
    image: postgres
    restart: always
    env_file: .db.env
    ports:
      - '5432:5432'
    volumes:
      - './docker-volumes/db/postgresql:/var/lib/postgresql/prosody'
    networks:
      - xmpp_chat
  xmpp_server:
    container_name: xmpp
    # image: unclev/prosody-docker-extended:0.10
    image: sameersbn/openfire
    restart: unless-stopped
    hostname: shakespeare.lit
    ports:
      # - 5222:5222
      # - 5269:5269
      # - 5347:5347
      # - 5280:5280
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
    env_file: .xmpp.env
    links: 
      - sql:sql
    volumes:
      - ./docker-volumes/openfire:/var/lib/openfire
      # - './docker-volumes/prosody/config:/etc/prosody'
      # - './docker-volumes/prosody/data:/var/lib/prosody'
      # - './docker-volumes/prosody/log:/var/log/prosody'
      # - './docker-volumes/prosody/modules/community:/usr/lib/prosody/modules-community'
      # - './docker-volumes/prosody/modules/custom:/usr/lib/prosody/modules-custom'
    networks:
      - xmpp_chat
networks: 
  xmpp_chat:
    driver: bridge